services:
  # ==========================================
  # ENTORNO QA (Pruebas)
  # ==========================================
  mongodb_qa:
    image: mongo:latest
    container_name: informes_mongodb_qa
    restart: always
    ports:
      - "8085:27017" # Puerto externo exclusivo para QA
    volumes:
      - datos_informes_uce_qa:/data/db

  api_qa:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: informes_api_qa
    restart: always
    ports:
      - "8082:4000" # Puerto exclusivo para QA
    volumes:
      - C:\Users\Lenovo LOQ\Desktop\Docentes_QA:/archivos_docentes # Carpeta de Escritorio aislada
    environment:
      - MONGODB_URI=mongodb://mongodb_qa:27017/sistema-informes-qa
      - FRONTEND_URL=http://10.1.1.1
      - ADMIN_CORREO=admin.qa@uce.edu.ec
      - ADMIN_CLAVE=admin123
      - ADMIN_CEDULA=0000000000
      - PERIODO_ACTUAL=2026-2026
      - UPLOAD_DIR=/archivos_docentes # 👈 Nueva variable para forzar la ruta
    depends_on:
      - mongodb_qa

  web_qa:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_BASE_PATH=/qa
        - NEXT_PUBLIC_API_URL=http://10.3.3.114/qa/api
    container_name: informes_web_qa
    restart: always
    ports:
      - "8081:3000"
    environment:
      - NEXT_PUBLIC_BASE_PATH=/qa
      - NEXT_PUBLIC_API_URL=http://10.3.3.114/qa/api
    depends_on:
      - api_qa
      
  # ==========================================
  # ENTORNO PRODUCCIÓN (Real)
  # ==========================================
  mongodb_prod:
    image: mongo:latest
    container_name: informes_mongodb_prod
    restart: always
    ports:
      - "8086:27017" # Puerto externo exclusivo para Producción
    volumes:
      - datos_informes_uce_prod:/data/db

  api_prod:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: informes_api_prod
    restart: always
    ports:
      - "8084:4000" # Puerto exclusivo para Producción
    volumes:
      - C:\Users\Lenovo LOQ\Desktop\Docentes_PROD:/archivos_docentes # Carpeta de Escritorio aislada
    environment:
      - MONGODB_URI=mongodb://mongodb_prod:27017/sistema-informes-prod
      - FRONTEND_URL=http://10.1.1.1
      - ADMIN_CORREO=admin@uce.edu.ec
      - ADMIN_CLAVE=admin123
      - ADMIN_CEDULA=0000000000
      - PERIODO_ACTUAL=2026-2026
      - UPLOAD_DIR=/archivos_docentes # 👈 Nueva variable para forzar la ruta
    depends_on:
      - mongodb_prod

  web_prod:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_BASE_PATH=/prod
        - NEXT_PUBLIC_API_URL=http://10.3.3.114/prod/api
    container_name: informes_web_prod
    restart: always
    ports:
      - "8083:3000"
    environment:
      - NEXT_PUBLIC_BASE_PATH=/prod
      - NEXT_PUBLIC_API_URL=http://10.3.3.114/prod/api
    depends_on:
      - api_prod

  # ==========================================
  # PROXY NGINX (Enrutador Web)
  # ==========================================
  proxy_nginx:
    image: nginx:alpine
    container_name: informes_nginx_proxy
    restart: always
    ports:
      - "80:80" # Único punto de entrada web unificado (IP del servidor)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web_qa
      - web_prod

# Declaración de los volúmenes aislados
volumes:
  datos_informes_uce_qa:
  datos_informes_uce_prod: