events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    # Fundamental para permitir subir PDFs pesados sin error 413
    client_max_body_size 100M;

    server {
        listen 80;
        server_name localhost;

        # ==========================================
        # 🟢 ENTORNO QA (Abierto a cualquier IP)
        # ==========================================
        location /qa/api/ {
            proxy_pass http://informes_api_qa:4000/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /qa/ {
            proxy_pass http://informes_web_qa:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # ==========================================
        # 🔴 ENTORNO PROD (Restringido a la UCE y Localhost)
        # ==========================================
        location /prod/api/ {
            allow 10.0.0.0/8;       # IPs internas de la Universidad (UCE)
            allow 127.0.0.1;        # Localhost IPv4 tradicional
            allow ::1;              # Localhost IPv6
            allow 172.16.0.0/12;    # Redes internas generales de Docker
            allow 192.168.65.0/24;  # Red específica de Docker Desktop en Windows
            
            deny all;               # Bloqueo total a cualquier otra IP

            proxy_pass http://informes_api_prod:4000/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /prod/ {
            allow 10.0.0.0/8;       # IPs internas de la Universidad (UCE)
            allow 127.0.0.1;        # Localhost IPv4 tradicional
            allow ::1;              # Localhost IPv6
            allow 172.16.0.0/12;    # Redes internas generales de Docker
            allow 192.168.65.0/24;  # Red específica de Docker Desktop en Windows
            
            deny all;               # Bloqueo total a cualquier otra IP

            proxy_pass http://informes_web_prod:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}